FROM s390x/ubuntu
MAINTAINER benjsmi@us.ibm.com

RUN apt-get update && apt-get install -y wget
RUN wget -O - https://downloads.opvis.bluemix.net:5443/client/IBM_Logmet_repo_install.sh | bash
RUN apt-get install -y collectd
# So we have collectd.  Next step is to build the mt-lumberjack plugin from source

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["collectd", "-f"]
